# Generated by Django 5.1.7 on 2025-07-12 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('full_address', models.TextField()),
                ('rt_rw', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('kabupaten', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('location_details', models.CharField(blank=True, max_length=255)),
                ('nama_alamat', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(blank=True, max_length=100)),
                ('receiver_phone', models.CharField(blank=True, max_length=20)),
                ('full_address', models.TextField(blank=True)),
                ('rt_rw', models.CharField(blank=True, max_length=20)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('kabupaten', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('location_details', models.CharField(blank=True, max_length=255)),
                ('nama_alamat', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
