# Generated by Django 5.1.7 on 2025-07-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_cart_created_at_cartitem_added_at_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_email', models.EmailField(max_length=254)),
                ('store_phone', models.CharField(max_length=20)),
                ('shipping_cost', models.PositiveIntegerField(default=0)),
                ('free_shipping_min', models.PositiveIntegerField(default=0)),
                ('enable_bank_transfer', models.BooleanField(default=True)),
                ('enable_cod', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
